FROM node:lts-alpine

WORKDIR /app

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV HOST 0.0.0.0

COPY ./frontend/package*.json ./

RUN npm install

COPY ./frontend/ .

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "serve-prod"]
