version: '3'
services:
  db:
    container_name: portfolio-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:5.7.12
    ports:
      - 33306:3306
    environment:
      - MYSQL_USER=${DJANGO_MYSQL_USER}
      - MYSQL_PASSWORD=${DJANGO_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DJANGO_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DJANGO_MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    container_name: portfolio-web
    build:
      context: backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DJANGO_MYSQL_HOST=${DJANGO_MYSQL_HOST}
      - DJANGO_MYSQL_PORT=${DJANGO_MYSQL_PORT}
      - DJANGO_MYSQL_USER=${DJANGO_MYSQL_USER}
      - DJANGO_MYSQL_PASSWORD=${DJANGO_MYSQL_PASSWORD}
      - DJANGO_MYSQL_DATABASE=${DJANGO_MYSQL_DATABASE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./backend:/app:cached
    depends_on:
      - db
  vue_web:
    container_name: portfolio-vue
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: sh
    command: -c "yarn install && yarn run serve"
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app:cached
    stdin_open: true
    tty: true
