version: '3'
services:
  db:
    container_name: portfolio-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:5.7.12
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    volumes:
      - ./mysql:/var/lib/mysql
  web:
    container_name: portfolio-web
    build:
      context: backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./backend:/app:cached
    depends_on:
      - db
  vue_web:
    container_name: portfolio-vue
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    entrypoint: sh
    command: -c "yarn install && yarn run serve"
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
