version: '3'
services:
  gunicorn:
    image: 909937076167.dkr.ecr.ap-northeast-1.amazonaws.com/django-vue-app-backend:latest
    container_name: gunicorn
    volumes:
      - gunicorn:/var/run/gunicorn
  nginx:
    image: 909937076167.dkr.ecr.ap-northeast-1.amazonaws.com/django-vue-app-nginx:latest
    container_name: nginx
    depends_on:
      - gunicorn
    ports:
      - "80:80"
    volumes:
      - gunicorn:/var/run/gunicorn
volumes:
  gunicorn:
